# Generated by Django 5.0.3 on 2024-08-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nails',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nails',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='nails.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='nails',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation', to='nails.creator'),
        ),
        migrations.AddField(
            model_name='nails',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='nails.tagpost'),
        ),
        migrations.AddIndex(
            model_name='nails',
            index=models.Index(fields=['-time_create'], name='nails_nails_time_cr_bf03e7_idx'),
        ),
    ]
